### ISSUE TITLE
Rmd header

### ISSUE THREAD

**Issue by markziemann** [markziemann/Gene-function-imputation#5]
https://github.com/markziemann/Gene-function-imputation/blob/ba143ae302a6eac2e97aa40c68c1b47005cccd77/YeastSampleQualityFilter.Rmd#L1

Here is an example Rmd header
```
---
title: "Yeast Sample Quality Filter "
author: "Megan Soria"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
theme: cosmo
---
```
